# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         URL-Grab
version:      1.2
version_from: lib/URL/Grab.pm
installdirs:  site
requires:
    Carp:                          0
    LWP::UserAgent:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
